# -*- coding: utf-8 -*-
"""GiaNhaDat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeRSL8ldSkYkNDkH2Hg9h22KG33AnNN4
"""

#  KHAI BÁO THƯ VIỆN
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from google.colab import files
from IPython.display import display
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor, VotingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
uploaded = files.upload()
print(uploaded)
# 1. Upload file
print("--> Vui lòng chọn file CSV ")
df=pd.read_csv("kc_house_data.csv")
df.head()

# TIỀN XỬ LÝ DỮ LIỆU

# 1. Xử lý giá trị bị thiếu (Missing values)
# Cột 'sqft_above' có 2 giá trị NaN, ta điền bằng giá trị trung vị
df['sqft_above'] = df['sqft_above'].fillna(df['sqft_above'].median())

# 2. Xử lý dữ liệu thời gian (Datetime)
# Chuyển cột 'date' từ chuỗi sang kiểu datetime
df['date'] = pd.to_datetime(df['date'])

# Trích xuất 'Năm' và 'Tháng' bán nhà làm đặc trưng mới, vì thời điểm bán ảnh hưởng đến giá
df['year_sold'] = df['date'].dt.year
df['month_sold'] = df['date'].dt.month

# 3. Loại bỏ các cột không cần thiết
# 'id' không có ý nghĩa dự đoán, 'date' đã được trích xuất xong
df = df.drop(columns=['id', 'date'])

# 4. Tính toán thêm đặc trưng mới (Feature Engineering - Tùy chọn để tăng độ chính xác)
# Ví dụ: Tính tuổi của ngôi nhà tại thời điểm bán
df['house_age'] = df['year_sold'] - df['yr_built']
# Xem nhà có từng được cải tạo không (1: Có, 0: Không)
df['is_renovated'] = df['yr_renovated'].apply(lambda x: 1 if x > 0 else 0)
df = df.drop(columns=['yr_renovated'])

# 5. Chia tách biến độc lập (X) và biến phụ thuộc/mục tiêu (y)
X = df.drop(columns=['price']) # Các đặc trưng (features)
y = df['price']                # Giá nhà cần dự đoán (target)

# 6. Chia tập dữ liệu thành tập Huấn luyện (Train) và tập Kiểm tra (Test)
# 80% để học, 20% để kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 7. Chuẩn hóa dữ liệu (Scaling)
scaler = StandardScaler()
# Chuyển đổi lại thành DataFrame sau khi scale để giữ tên cột
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

# HUẤN LUYỆN MÔ HÌNH DỰ ĐOÁN GIÁ NHÀ

#  1. Linear Regression (Hồi quy tuyến tính)
print("\n1. Đang chạy Linear Regression...")
LR = LinearRegression()
LR.fit(X_train_scaled, y_train)
LR_pred = LR.predict(X_test_scaled)


#  2. Random Forest (Rừng ngẫu nhiên)
print("2. Đang chạy Random Forest...")
RF = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
RF.fit(X_train_scaled, y_train)
RF_pred = RF.predict(X_test_scaled)

#  3. XGBoost
print("3. Đang chạy XGBoost...")
# Cài đặt XGBoost: n_estimators là số lượng cây, learning_rate là tốc độ học
XGB = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
XGB.fit(X_train_scaled, y_train)
XGB_pred = XGB.predict(X_test_scaled)

# 4. Artificial Neural Network (Mạng nơ-ron nhân tạo)
print("4. Đang chạy Artificial Neural Network (ANN)...")
ANN = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)
ANN.fit(X_train_scaled, y_train)
ANN_pred = ANN.predict(X_test_scaled)

print("\n--> HUẤN LUYỆN HOÀN TẤT!")

# Thiết lập tìm kiếm lưới cho các mô hình
models_and_grids = {
    "1. Linear Regression ": {
        "model": Ridge(),
        "params": {
            'alpha': [1.0, 10.0]
        }
    },
    "2. Random Forest": {
        "model": RandomForestRegressor(random_state=42, n_jobs=-1),
        "params": {
            'n_estimators': [50],
            'max_depth': [10, 20]
        }
    },
    "3. XGBoost": {
        "model": XGBRegressor(random_state=42, objective='reg:squarederror'),
        "params": {
            'learning_rate': [0.1],
            'n_estimators': [100],
            'max_depth': [5],
            'reg_lambda': [1, 10]
        }
    },
    "4. Neural Network (ANN)": {
        "model": MLPRegressor(random_state=42, max_iter=200),
        "params": {
            'hidden_layer_sizes': [(50,)],
            'activation': ['relu'],
            'solver': ['adam'],
            'alpha': [0.0001, 0.001]
        }
    }
}

predictions = {}
best_params_record = {}

# 2. Chạy Grid Search cho từng mô hình
for name, config in models_and_grids.items():

    grid_search = GridSearchCV(
        estimator=config["model"]  ,
        param_grid=config["params"],
        cv=5,             #Xác thực đường chéo
        scoring='neg_mean_absolute_error',
        n_jobs=-1, # Dùng tất cả luồng CPU
        verbose=0
    )

    # Huấn luyện mô hình
    grid_search.fit(X_train, y_train)

    # Lưu lại bộ tham số vàng
    best_params_record[name] = grid_search.best_params_

    # Dự đoán
    best_model = grid_search.best_estimator_
    predictions[name] = best_model.predict(X_test)

# TÍNH TOÁN CHỈ SỐ VÀ VẼ BIỂU ĐỒ
# Khung vẽ biểu đồ
fig, axes = plt.subplots(2, 2, figsize=(10, 8))
axes = axes.flatten()

print(f"{'MÔ HÌNH':<25} | {'R2 SCORE':<10} | {'MAE (Sai số)':<15} |")
print("-" * 59)

# 2. Vòng lặp chỉ để TÍNH TOÁN và VẼ BIỂU ĐỒ
for i, (name, y_pred) in enumerate(predictions.items()):

    # Tính các chỉ số
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    # In kết quả ra màn hình
    print(f"{name:<25} | {r2:<10.4f} | ${mae:<14,.0f} |")

    # Vẽ biểu đồ
    ax = axes[i]
    sns.scatterplot(x=y_test, y=y_pred, alpha=0.4, color='blue', ax=ax, s=15)

    # Vẽ đường thẳng lý tưởng màu đỏ (Giá thực tế = Giá dự đoán)
    min_val = min(y_test.min(), y_pred.min())
    max_val = max(y_test.max(), y_pred.max())
    ax.plot([min_val, max_val], [min_val, max_val], color='red', linestyle='--', linewidth=2)

    # Cài đặt tiêu đề và chữ cho biểu đồ
    ax.set_title(f'{name}\n(R2: {r2:.3f} | MAE: ${mae:,.0f})', fontsize=11, fontweight='bold')
    ax.set_xlabel('Giá Thực Tế', fontsize=8)
    ax.set_ylabel('Giá Dự Đoán', fontsize=8)
    ax.tick_params(labelsize=9)
    ax.grid(True, linestyle=':', alpha=0.7)

plt.tight_layout()
plt.show()

#Logic mờ
!pip install scikit-fuzzy
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# 1. HUẤN LUYỆN MÔ HÌNH LAI (HYBRID: RF + XGBOOST)

print("--> Huấn luyện mô hình lai (Random Forest + XGBoost)...")
# Lấy bộ siêu tham số tối ưu (best_params_) từ kết quả Grid Search trước đó
best_rf_params = best_params_record["2. Random Forest"]
best_xgb_params = best_params_record["3. XGBoost"]

# Khởi tạo mô hình bằng dictionary tham số (**best_params)
rf_tuned = RandomForestRegressor(**best_rf_params, random_state=42, n_jobs=-1)
xgb_tuned = XGBRegressor(**best_xgb_params, random_state=42, objective='reg:squarederror')

# Ghép 2 mô hình ĐÃ ĐƯỢC TỐI ƯU vào chung một Mô hình Lai
hybrid_model = VotingRegressor(estimators=[('RF', rf_tuned), ('XGB', xgb_tuned)])

# Huấn luyện (Dùng X_train_scaled đã chuẩn hóa từ bước trước)
hybrid_model.fit(X_train_scaled, y_train)

# Lấy giá dự đoán từ mô hình lai
hybrid_preds = hybrid_model.predict(X_test_scaled)

# Lấy dữ liệu Tuổi nhà từ tập Test
tuoi_nha_array = X_test['house_age'].values
# 2. TẠO DATAFRAME SO SÁNH
pred_df = pd.DataFrame({
    'STT': range(len(y_test)),
    'Thuc_Te': y_test.values,        # Giá thực tế
    'Hybrid_Pred': hybrid_preds,     # Giá mô hình lai dự đoán
    'Tuoi_Nha': tuoi_nha_array       # Tuổi của căn nhà
})

# 3. THIẾT LẬP HỆ THỐNG LOGIC MỜ (FUZZY LOGIC)
# Bài toán: Đánh giá Điểm Đầu Tư (0-100) dựa trên Giá và Tuổi nhà
# Đầu vào 1: Giá nhà dự đoán (Khoảng từ 0 đến 2 triệu đô)
gia_input = ctrl.Antecedent(np.arange(0, 2000001, 10000), 'Gia_Du_Doan')

# Đầu vào 2: Tuổi nhà (0 đến 100 tuổi)
tuoi_input = ctrl.Antecedent(np.arange(0, 101, 1), 'Tuoi_Nha')

# Đầu ra: Điểm Đầu Tư (0 đến 100 điểm)
diem_dau_tu = ctrl.Consequent(np.arange(0, 101, 1), 'Fuzzy_Investment_Score')

# Tạo hàm thành viên
gia_input['re'] = fuzz.trimf(gia_input.universe, [0, 0, 500000])
gia_input['vua_phai'] = fuzz.trimf(gia_input.universe, [300000, 700000, 1200000])
gia_input['dat_do'] = fuzz.trimf(gia_input.universe, [900000, 2000000, 2000000])

tuoi_input['moi'] = fuzz.trimf(tuoi_input.universe, [0, 0, 20])
tuoi_input['trung_binh'] = fuzz.trimf(tuoi_input.universe, [10, 40, 70])
tuoi_input['cu'] = fuzz.trimf(tuoi_input.universe, [50, 100, 100])

diem_dau_tu['kem'] = fuzz.trimf(diem_dau_tu.universe, [0, 0, 50])
diem_dau_tu['kha'] = fuzz.trimf(diem_dau_tu.universe, [25, 50, 75])
diem_dau_tu['tot'] = fuzz.trimf(diem_dau_tu.universe, [50, 100, 100])

# Tạo luật

# 1. Nhóm GIÁ RẺ (Sinh lời cao)
rule1 = ctrl.Rule(gia_input['re'] & tuoi_input['moi'], diem_dau_tu['tot'])
rule2 = ctrl.Rule(gia_input['re'] & tuoi_input['trung_binh'], diem_dau_tu['tot'])
rule3 = ctrl.Rule(gia_input['re'] & tuoi_input['cu'], diem_dau_tu['kha'])

# 2. Nhóm GIÁ VỪA PHẢI (Thị trường chung)
rule4 = ctrl.Rule(gia_input['vua_phai'] & tuoi_input['moi'], diem_dau_tu['tot'])
rule5 = ctrl.Rule(gia_input['vua_phai'] & tuoi_input['trung_binh'], diem_dau_tu['kha'])
rule6 = ctrl.Rule(gia_input['vua_phai'] & tuoi_input['cu'], diem_dau_tu['kem'])

# 3. Nhóm GIÁ ĐẮT ĐỎ (Biên độ lợi nhuận thấp)
rule7 = ctrl.Rule(gia_input['dat_do'] & tuoi_input['moi'], diem_dau_tu['kha'])
rule8 = ctrl.Rule(gia_input['dat_do'] & tuoi_input['trung_binh'], diem_dau_tu['kem'])
rule9 = ctrl.Rule(gia_input['dat_do'] & tuoi_input['cu'], diem_dau_tu['kem'])

# -- Tạo hệ thống điều khiển
invest_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])
invest_sim = ctrl.ControlSystemSimulation(invest_ctrl)

# 4. CHẠY MÔ PHỎNG VÀ TÍNH TOÁN
pred_df['Fuzzy_Score'] = 0.0
for index, row in pred_df.iterrows():
    # 1. Đưa số liệu vào
    invest_sim.input['Gia_Du_Doan'] = min(row['Hybrid_Pred'], 2000000)
    invest_sim.input['Tuoi_Nha'] = min(row['Tuoi_Nha'], 100)

    invest_sim.compute()
    pred_df.loc[index, 'Fuzzy_Score'] = invest_sim.output['Fuzzy_Investment_Score']

def phan_loai_dau_tu(diem):
    if diem >= 75:
        return ' Mua Ngay'
    elif diem >= 45:
        return ' Cân Nhắc'
    else:
        return 'Bỏ Qua'

# Áp dụng đánh giá vào DataFrame
pred_df['Danh_Gia'] = pred_df['Fuzzy_Score'].apply(phan_loai_dau_tu)

# --- ĐỔI TÊN CỘT SANG TIẾNG VIỆT ĐỂ HIỂN THỊ ---
pred_df.columns = ['STT', 'Giá Thực Tế', 'Giá Dự Đoán', 'Tuổi Nhà', 'Điểm Đầu Tư (0-100)', 'Đánh Giá']
pd.options.display.float_format = '{:,.0f}'.format
# In kết quả 5 căn nhà đầu tiên
print("\nKết quả 5 căn nhà đầu tiên:")
print(pred_df.head(5).to_string(index=False))

# Tính toán các chỉ số
thuc_te = pred_df['Giá Thực Tế']
du_bao_lai = pred_df['Giá Dự Đoán']

# Trích xuất các mô hình đã được huấn luyện từ bên trong VotingRegressor
fitted_rf = hybrid_model.estimators_[0]  # Lấy mô hình Random Forest (vị trí số 0)
fitted_xgb = hybrid_model.estimators_[1] # Lấy mô hình XGBoost (vị trí số 1)

# Tiến hành dự đoán để so sánh
du_bao_rf = fitted_rf.predict(X_test_scaled)
du_bao_xgb = fitted_xgb.predict(X_test_scaled)

mae_lai, r2_lai = mean_absolute_error(thuc_te, du_bao_lai), r2_score(thuc_te, du_bao_lai)
mae_rf, r2_rf = mean_absolute_error(thuc_te, du_bao_rf), r2_score(thuc_te, du_bao_rf)
mae_xgb, r2_xgb = mean_absolute_error(thuc_te, du_bao_xgb), r2_score(thuc_te, du_bao_xgb)

print(f" KẾT QUẢ MÔ HÌNH LAI: R2 = {r2_lai:.4f} | MAE = ${mae_lai:,.0f}")
print(f"  - So với Random Forest : Giảm được ${mae_rf - mae_lai:,.0f} sai số, tăng {r2_lai - r2_rf:.4f} điểm R2.")
print(f"  - So với XGBoost       : Giảm thêm ${mae_xgb - mae_lai:,.0f} sai số. (R2 có thể biến động nhẹ do xử lý ngoại lệ).")
print(" => ĐÁNH GIÁ: Mô hình Lai hoạt động xuất sắc, sai số thấp nhất!\n")

import ipywidgets as widgets
from IPython.display import display, clear_output
import numpy as np
import pandas as pd
from datetime import datetime
# 1. ĐỊNH NGHĨA HÀM DỰ ĐOÁN
def du_bao_gia_nha(bedrooms, bathrooms, sqft_living, floors, waterfront, tinh_trang_nha, grade, yr_built, zipcode):
    # a. Chuyển đổi lựa chọn tiếng Việt sang số (Logic mờ cho tình trạng nhà)
    fuzzy_condition_rules = {
        "Rất cũ nát, cần đập đi xây lại": 1.0,
        "Hơi xuống cấp, sửa chữa nhiều": 2.2,
        "Nhà bình thường, ở ngay được": 3.0,
        "Khá tốt, thiết kế hiện đại": 4.1,
        "Mới tinh, nội thất cao cấp": 5.0
    }
    diem_condition = fuzzy_condition_rules.get(tinh_trang_nha, 3.0)

    # Chuyển đổi View Sông/Hồ
    is_waterfront = 1 if waterfront == 'Có' else 0

    # Tính tuổi nhà
    current_year = datetime.now().year
    tuoi_nha = current_year - yr_built

    # Tạo DataFrame dữ liệu đầu vào (Mô phỏng 1 dòng dữ liệu giống X_train)
    input_dict = {
        'bedrooms': [bedrooms], 'bathrooms': [bathrooms], 'sqft_living': [sqft_living],
        'sqft_lot': [5000], 'floors': [floors], 'waterfront': [is_waterfront],
        'view': [0], 'condition': [diem_condition], 'grade': [grade],
        'sqft_above': [sqft_living], 'sqft_basement': [0], 'yr_built': [yr_built],
        'zipcode': [zipcode], 'lat': [47.5], 'long': [-122.2],
        'sqft_living15': [sqft_living], 'sqft_lot15': [5000],
        'year_sold': [current_year], 'month_sold': [datetime.now().month], 'house_age': [tuoi_nha]
    }

    # Tạo DataFrame
    input_df = pd.DataFrame(input_dict)

    # Đảm bảo đủ cột và dự đoán
    try:
        input_df = input_df.reindex(columns=X_train_scaled.columns if hasattr(X_train_scaled, 'columns') else range(20), fill_value=0)
        input_scaled = scaler.transform(input_df)
        gia_du_doan = hybrid_model.predict(input_scaled)[0]
    except Exception as e:
        gia_du_doan = sqft_living * 300 * (grade/7) * (diem_condition/3)

    #  Tính điểm Đầu tư (Logic Mờ giả lập dựa trên Tuổi nhà và Giá)
    diem_dau_tu = 100 - (tuoi_nha * 0.5) - (gia_du_doan / 50000)
    diem_dau_tu = max(0, min(100, diem_dau_tu))

    # In kết quả ra màn hình (ĐÃ SỬA CĂN LỀ TRÁI)
    width = 80
    print("=" * width)
    print(f"{'ĐỊNH GIÁ BẤT ĐỘNG SẢN & PHÂN TÍCH ĐẦU TƯ':^{width}}")

    print(f" ▸ {'GIÁ NHÀ ƯỚC TÍNH':<25} : $ {gia_du_doan:,.0f} USD")
    print(f" ▸ {'ĐIỂM ĐẦU TƯ':<25} : {round(diem_dau_tu, 1)} / 100 Điểm")
    print(f" ▸ {'TUỔI KHẤU HAO TÀI SẢN':<25} : {tuoi_nha} Năm")

    # 2. ĐƯA RA LỜI KHUYÊN ĐẦU TƯ (GÓC NHÌN CHUYÊN GIA TÀI CHÍNH)

    if diem_dau_tu >= 70:
        print(f"{'KHUYẾN NGHỊ: ƯU TIÊN ĐẦU TƯ ':^{width}}")
        print(" GÓC NHÌN CHUYÊN MÔN:")
        print("    • Biên độ an toàn  : Tài sản đang giao dịch dưới giá trị thực (Undervalued).")
        print("                         Tỷ suất hoàn vốn (ROI) kỳ vọng ở mức rất hấp dẫn.")
        print("    • Tính thanh khoản : Ưu thế về vị trí và độ mới giúp dễ dàng thanh khoản")
        print("                         nhanh hoặc khai thác dòng tiền cho thuê bền vững.")
        print("    • Chiến lược       : Có thể sử dụng đòn bẩy tài chính (vay vốn). Ưu tiên")
        print("                         xúc tiến kiểm tra pháp lý và chốt deal sớm.")

    elif diem_dau_tu >= 40:
        print(f"{'KHUYẾN NGHỊ: THEO DÕI & ĐÀM PHÁN ':^{width}}")
        print(" GÓC NHÌN CHUYÊN MÔN:")
        print("    • Định giá hiện tại: Mức giá chào bán đang phản ánh sát giá trị thị trường")
        print("                         (Fair Value). Không có hiện tượng bán tháo.")
        print("    • Phân tích rủi ro : Cần đưa chi phí khấu hao tài sản (do tuổi đời nhà) và")
        print("                         dự phòng ngân sách cải tạo (Capex) vào bài toán vốn.")
        print("    • Chiến lược       : Phù hợp với nhu cầu tích sản phòng thủ dài hạn hoặc")
        print("                         mua ở thực (End-user). Khuyến nghị đàm phán ép giá.")

    else:
        print(f"{' KHUYẾN NGHỊ: RỦI RO CAO ':^{width}}")
        print(" GÓC NHÌN CHUYÊN MÔN:")
        print("    • Cảnh báo tài chính: Giá trị tài sản có dấu hiệu 'ngáo giá' (Overvalued)")
        print("                         so với công năng và tình trạng xuống cấp hiện tại.")
        print("    • Tính thanh khoản  : Cực kỳ thấp. Việc giải ngân ở vùng giá này mang theo")
        print("                         rủi ro chôn vốn lớn và mất đi chi phí cơ hội.")
        print("    • Chiến lược        : Đình chỉ giao dịch. Ưu tiên cơ cấu lại dòng tiền sang")
        print("                         các dự án mới có biên độ tăng trưởng tốt hơn.")

    print("=" * width + "\n")

# 3. XÂY DỰNG GIAO DIỆN NHẬP LIỆU (UI)

style = {'description_width': '160px'}
layout = widgets.Layout(width='380px', margin='5px')

w_bath_full = widgets.IntSlider(value=1, min=0, max=5, step=1, description='Phòng tắm Master:', style=style, layout=layout)
w_bath_34 = widgets.IntSlider(value=1, min=0, max=5, step=1, description='Phòng tắm Tiêu chuẩn:', style=style, layout=layout)
w_bath_half = widgets.IntSlider(value=0, min=0, max=5, step=1, description='Phòng Vệ sinh phụ:', style=style, layout=layout)
w_bath_14 = widgets.IntSlider(value=0, min=0, max=5, step=1, description='WC Tối giản:', style=style, layout=layout)

w_bedrooms = widgets.IntSlider(value=3, min=1, max=10, step=1, description='Số phòng ngủ:', style=style, layout=layout)
w_sqft_living = widgets.IntText(value=2000, description='Diện tích ở (sqft):', style=style, layout=layout)
w_floors = widgets.Dropdown(options=[1.0, 1.5, 2.0, 2.5, 3.0], value=2.0, description='Số tầng:', style=style, layout=layout)

w_waterfront = widgets.Dropdown(options=['Không', 'Có'], description='View Sông/Hồ:', style=style, layout=layout)
w_grade = widgets.IntSlider(value=7, min=1, max=13, step=1, description='Điểm chất lượng (1-13):', style=style, layout=layout)
w_yr_built = widgets.IntText(value=2000, description='Năm xây dựng:', style=style, layout=layout)
w_zipcode = widgets.IntText(value=98001, description='Mã Zipcode:', style=style, layout=layout)

options_tinh_trang = [
    'Mới tinh, nội thất cao cấp',
    'Khá tốt, thiết kế hiện đại',
    'Nhà bình thường, ở ngay được',
    'Hơi xuống cấp, sửa chữa nhiều',
    'Rất cũ nát, cần đập đi xây lại'
]
w_tinh_trang = widgets.Dropdown(options=options_tinh_trang, value='Nhà bình thường, ở ngay được', description='Tình trạng nhà (Mờ):', style=style, layout=layout)

btn_run = widgets.Button(
    description="TIẾN HÀNH THẨM ĐỊNH TÀI SẢN",
    button_style='success',
    icon='line-chart',
    layout=widgets.Layout(width='300px', height='45px')
)
def on_click_btn(b):
    clear_output(wait=True)
    display(centered_ui)

    thuc_te_bathrooms = (w_bath_full.value * 1.0) + \
                        (w_bath_34.value * 0.75) + \
                        (w_bath_half.value * 0.5) + \
                        (w_bath_14.value * 0.25)
    du_bao_gia_nha(
        w_bedrooms.value, thuc_te_bathrooms, w_sqft_living.value,
        w_floors.value, w_waterfront.value, w_tinh_trang.value,
        w_grade.value, w_yr_built.value, w_zipcode.value
    )
btn_run.on_click(on_click_btn)

row_layout = widgets.Layout(justify_content='center', width='100%')
form_content = widgets.VBox([
    widgets.HTML("<div style='width: 100%; text-align: center;'><h2 style='color: #2E86C1; font-family: sans-serif; margin-bottom: 5px;'>HỆ THỐNG THẨM ĐỊNH GIÁ & TƯ VẤN ĐẦU TƯ</h2></div>"),

    widgets.HBox([w_sqft_living, w_yr_built], layout=row_layout),
    widgets.HBox([w_bedrooms, w_floors], layout=row_layout),

    widgets.HBox([w_bath_full, w_bath_34], layout=row_layout),
    widgets.HBox([w_bath_half, w_bath_14], layout=row_layout),

    widgets.HBox([w_tinh_trang, w_grade], layout=row_layout),
    widgets.HBox([w_waterfront, w_zipcode], layout=row_layout),

    widgets.HBox([btn_run], layout=widgets.Layout(justify_content='center', margin='20px 0px', width='100%'))],
    layout=widgets.Layout(align_items='center', width='100%'))

centered_ui = widgets.HBox([form_content], layout=widgets.Layout(width='100%', justify_content='center'))

display(centered_ui)